### ISSUE TITLE
Especificar nombre de App

### ISSUE THREAD

**Issue by dfernq** [MrJorgx/PracticaFinalINSO---CunadoPay#1]
Sólo veo en una de las vistas la siguiente referencia: `Bienvenido a CuñadoPay`, pero no tengo este nombre de aplicación registrado en ningún grupo de prácticas. Tampoco puedo identificaros con el nombre de usuario de GitHub (@MrJorgx) que habéis usado para añadirme como colaborador.

Plz, especificar en algún sitio: nombre de aplicación e integrantes del grupo. Thx!

**Comment by MrJorgx** [comment]
He realizado los cambios, ahora en el README aparece el nombre de la aplicación y los integrantes del grupo, todavía falta por añadir un colaborador(Gonzalo).

**Comment by dfernq** [comment]
visto, gracias!
